### ISSUE TITLE
USD fiat pair

### ISSUE THREAD

**Issue by fogoat** [SmartCash/electrum-smart#11]
Can electrum have USD fiat pair? Its not on the list.

**Comment by rc125** [comment]
We already have!

<img width="436" alt="usd-fiat-pair" src="https://user-images.githubusercontent.com/2768605/50592622-abed6300-0e73-11e9-9552-ab0f2b7f8713.png">

**Comment by fogoat** [comment]
Okay I don't see it on mine for some reason. I think I have history rates on. In USA, for taxes you need to show value of coin bought or sold on that day.
