### ISSUE TITLE
Link to blockexplorer does not work when right-clicking on address

### ISSUE THREAD

**Issue by radonsoft** [SmartCash/electrum-smart#2]
- Open Addresses tab of wallet
- Right-click an address
- Select "View on block explorer"
The wallet will try to open a page blockchain:/address/Sxxxxxxxx which obviously does not work

Right-click and select "View on block explorer" on addressed in Contacts does not seem to work at all.

**Comment by radonsoft** [comment]
When selecting "Smart Explorer" or "Rpc Explorer" in Preferences -> Appearance, Addresses in Addresses tab of wallet work -- Contacts still do not. 

Maybe remove the "system default option" for the explorer selection in Preferences->Appearance ?

**Comment by rc125** [comment]
Removed the "system default option"! Solved in https://github.com/SmartCash/electrum-smart/commit/2fff528c736212dc72465501c24d3356c9b670a6
