### ISSUE TITLE
У моего кошелька нет подключения

### ISSUE THREAD

**Issue by Natarella** [SmartCash/electrum-smart#57]
давно не заходила в кошелек, была версия 4.0.5. Сегодня зашла, горит красным кнопка Нет связи, что дальше делать?

**Comment by Martysz14** [comment]
У меня такая же проблема, обновила до новой версии, но все равно не подключен. Написала на все возможные форумы пока ответа нет. Если что-то узнаете дайте знать пожалуйста.
