### ISSUE TITLE
hardcoding?

### ISSUE THREAD

**Issue by jkhales** [SmartCash/electrum-smart#8]
On ubuntu linux it throws the error:

bash: /usr/local/bin/electrum-smart: /home/rc125/.pyenv/versions/3.6.4/bin/python3: bad interpreter: No such file or directory

When I run electrum-smart on the command line.

Noticed it looks like the home directory of the repo owner...

**Comment by rc125** [comment]
Which version are you trying to run?

**Comment by jkhales** [comment]
I was following these instructions:
sudo apt-get install python3-setuptools python3-pyqt5 python3-pip && sudo pip3 install https://github.com/SmartCash/electrum-smart/releases/download/v3.1.2/Linux.Electrum-smart-3.1.2.tar.gz

**Comment by rc125** [comment]
The release has been updated, please try again. Tested on ubuntu 18.04 and worked well

**Comment by jkhales** [comment]
will check tomorrow morning!

**Comment by jkhales** [comment]
Success! Thanks for your quick fix!!
